### ISSUE TITLE
本地分支不push也能提测感觉不安全

### ISSUE THREAD

**Issue by dzh6699** [xiaolyuh/mrtf-git-flow-4idea#11]
提测的时候本地分支没有检测是否已经push，导致经常出现一些问题

**Comment by dzh6699** [comment]
建议提测的时候自动push一次

**Comment by xiaolyuh123** [comment]
> 提测的时候本地分支没有检测是否已经push，导致经常出现一些问题

什么问题

**Comment by dzh6699** [comment]
偶尔有人代码忘记push，然后提测没问题，合并到生产出现bug

**Comment by dzh6699** [comment]
建议大佬考虑下，提测前将当前分支push到远端，然后再切换分支做merger操作

**Comment by xiaolyuh123** [comment]
没有明白哪里会不安全了


发自我的iPhone
