### ISSUE TITLE
这是要自己打包么

### ISSUE THREAD

**Issue by ciweigg2** [xiaolyuh/mrtf-git-flow-4idea#3]
有打好的包么 自己编译有点问题 下载不下来

**Comment by xiaolyuh123** [comment]
有啊  github  选release就可以看到了


发自我的iPhone

**Comment by ciweigg2** [comment]
我直接下载最新的release 1. 0. 6在2020.1中安装不了 下载编译把2018.1改成2020.1后编译是成功了 但是点发布完成后报错 你release地址能给我个嘛 我看到的都是源码。。。谢谢啦

**Comment by ciweigg2** [comment]
看到最新版有了 就1.0.6没有zip

**Comment by xiaolyuh123** [comment]
这里可以下载到最新的了，支持2020.1

https://plugins.jetbrains.com/plugin/14056-gitflowplus/versions


发自我的iPhone

**Comment by xiaolyuh123** [comment]
在 2020-04-28 08:31:20，"xiaolyuh@163.com" <xiaolyuh@163.com> 写道：

这里可以下载到最新的了，支持2020.1


https://plugins.jetbrains.com/plugin/14056-gitflowplus/versions



发自我的iPhone

在 2020年4月27日，下午7:29，ciweigg2 <notifications@github.com> 写道：


﻿

看到最新版有了 就1.0.6没有zip
