### ISSUE TITLE
关于动态远程仓库名的意见

### ISSUE THREAD

**Issue by yurenzhen** [xiaolyuh/mrtf-git-flow-4idea#4]
通常情况下, 我们填写一个git远程仓库地址后都会默认命名为 origin, 这个与mrtf-git-flow里面的编码是一样的.

但若添加git远程仓库地址后都不命名为origin, 而是其他名字, 则与mrtf-git-flow里面的硬编码就不一样了, 提示找不到 origin这个远程仓库, 从而无法初始化mrtf-git-flow, 而其后的其他功能自然也就没法使用.

建议在初始化mrtf-git-flow的界面把远程仓库的名称也作为一个参数变量, 其默认值是origin, 但是允许用户自己修改为其他值.

**Comment by xiaolyuh123** [comment]
非常感谢您的建议
