### ISSUE TITLE
重建测试分支的时候为什么是会操作release分支呢，而不去操作test分支？

### ISSUE THREAD

**Issue by isinry** [xiaolyuh/mrtf-git-flow-4idea#5]
![image](https://user-images.githubusercontent.com/27894034/81916887-0588a480-9607-11ea-8b6f-b94612532c71.png)
![image](https://user-images.githubusercontent.com/27894034/81916906-0e797600-9607-11ea-8458-8efa85e18147.png)

**Comment by xiaolyuh123** [comment]
在最新的1.0.10版本中已修复，谢谢你的建议！
