### ISSUE TITLE
如何创建一个develop分支

### ISSUE THREAD

**Issue by Andy045** [xiaolyuh/mrtf-git-flow-4idea#8]
你好，git flow流程中还有一个develop分支，发布前多人协同开发marge会用到。在插件中没找到develop的支持

**Comment by Andy045** [comment]
貌似和你们在用的flow流程中 test分支作用很像，

**Comment by Andy045** [comment]
看到csdn的文章了 感谢分享

**Comment by xiaolyuh123** [comment]
使用方式可以去看插件主页，哪里有使用录屏。



发自我的iPhone
